{
 "title": "Ruckus",
 "tags": [
  "Ruckus",
  "SNMP",
  "Network"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "master",
    "label": "Master",
    "query": {
     "query": "label_values(ruckus_unleashed_ap_status,instance)"
    }
   },
   {
    "name": "ap",
    "label": "AP",
    "query": {
     "query": "label_values(ruckus_unleashed_ap_status{instance=~\"$master\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Quick Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ruckus_unleashed_ap_status{instance=~\"$master\",role=\"master\"} != 0"
    },
    {
     "expr": "ruckus_unleashed_controller_uptime_seconds{instance=~\"$master\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ruckus_unleashed_controller_memory_usage_percent{instance=~\"$master\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ruckus_unleashed_controller_cpu_usage_percent{instance=~\"$master\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ruckus_unleashed_network_aps_total{instance=~\"$master\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ruckus_unleashed_network_clients_total{instance=~\"$master\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Master uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ruckus_unleashed_controller_uptime_seconds{instance=~\"$master\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Master CPU Utlilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ruckus_unleashed_controller_cpu_usage_percent{instance=~\"$master\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Master Memory utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(ruckus_unleashed_controller_memory_usage_percent{instance=~\"$master\"}[15m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "WiFi", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Total # of APs",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ruckus_unleashed_ap_status{instance=~\"$master\"}!=0)"
    }
   ]
  },
  {
   "title": "Total # of APs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (instance)(ruckus_unleashed_ap_status{instance=~\"$master\"}!=0)",
     "legendFormat": "{{instance}} Active APs"
    }
   ]
  },
  {
   "title": "Total # of WiFi Clients",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(ruckus_unleashed_network_clients_total{instance=~\"$master\"}[15m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total # of WiFi Clients",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "last_over_time(ruckus_unleashed_network_clients_total{instance=~\"$master\"}[15m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "APs",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "ruckus_unleashed_ap_uptime_seconds{instance=~\"$master\",name=~\"$ap\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ruckus_unleashed_ap_clients{instance=~\"$master\",name=~\"$ap\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ruckus_unleashed_ap_cpu_utilization{instance=~\"$master\",name=~\"$ap\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ruckus_unleashed_ap_memory_usage_percent{instance=~\"$master\",name=~\"$ap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# of clients per AP",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum by (name) (ruckus_unleashed_ap_clients{instance=~\"$master\",name=~\"$ap\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "# of clients by connection quality",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by (name,quality) (ruckus_unleashed_ap_client_signal_quality_count{instance=~\"$master\",name=~\"$ap\",quality=\"good\"})",
     "legendFormat": "{{name}} - {{quality}} connection"
    },
    {
     "expr": "sum by (name,quality) (ruckus_unleashed_ap_client_signal_quality_count{instance=~\"$master\",name=~\"$ap\",quality=\"moderate\"})",
     "legendFormat": "{{name}} - {{quality}} connection"
    },
    {
     "expr": "sum by (name,quality) (ruckus_unleashed_ap_client_signal_quality_count{instance=~\"$master\",name=~\"$ap\",quality=\"poor\"})",
     "legendFormat": "{{name}} - {{quality}} connection"
    }
   ]
  },
  { "title": "CPU / Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Master CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "last_over_time(ruckus_unleashed_controller_cpu_usage_percent{instance=~\"$master\"}[15m])",
     "legendFormat": "{{instance}} CPU Utilization"
    }
   ]
  },
  {
   "title": "Master memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "last_over_time(ruckus_unleashed_controller_memory_usage_percent{instance=~\"$master\"}[15m])",
     "legendFormat": "{{instance}} Memory Utilization"
    }
   ]
  },
  {
   "title": "AP CPU Utlilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (name) (last_over_time(ruckus_unleashed_ap_cpu_utilization{instance=~\"$master\",name=~\"$ap\"}[15m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "AP memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (name) (ruckus_unleashed_ap_memory_usage_percent{instance=~\"$master\",name=~\"$ap\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Ruckus network upload",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(ruckus_unleashed_network_tx_bytes_total{instance=~\"$master\"}[15m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Ruckus network download",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(ruckus_unleashed_network_rx_bytes_total{instance=~\"$master\"}[15m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Exporter Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Exporter Scrape Time",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ruckus_exporter_scrape_duration_seconds{instance=~\"$master\",quantile=\"0.99\",module!=\"total\"}",
     "legendFormat": "{{instance}} - {{module}}"
    }
   ]
  }
 ]
}